# Final Practical: Classification using scikit-learn and MLflow

In this practical, you will use a Scikit-learn dataset (you may use the same as in the Intro MLflow notebook) to train a classification model.

Steps to follow:

    Data exploration: Analyze the provided dataset to understand its structure and content.

    Text preprocessing: Perform text preprocessing tasks such as tokenization and vectorization to prepare the data for modeling.

    Model training: Use Scikit-learn classification algorithms to train a model with the preprocessed data.

    Model evaluation: Evaluate the model’s performance using standard evaluation metrics such as accuracy and recall.

    Metrics logging using MLflow: Use MLflow to log metrics and hyperparameters during training, making it easier to manage and compare experiments.


Note: Since I will not be able to access your MLflow logs, please include screenshots of the MLflow interface in the notebook.

In [1]:
# ====================================================
# =====    Initial installation in notebook      =====
# ===== (then restart kernel and skip this step) =====
# ====================================================

import os
import sys
import subprocess
from importlib.metadata import version, PackageNotFoundError

# Define required packages and versions
required = {
    "pandas": ">=2.0.0",
    "numpy": ">=1.25.0",
    "scikit-learn": "==1.8.0",
    "spacy": ">=3.7.0",
    "nltk": ">=3.8.0",
    "mlflow": "==3.10.0",
    "matplotlib": ">=3.8.0",
    "seaborn": ">=0.13.0",
}

to_install = []

for pkg, ver_spec in required.items():
    try:
        installed_version = version(pkg)
        # Simple check: if exact version required, compare directly
        if ver_spec.startswith("==") and installed_version != ver_spec[2:]:
            to_install.append(f"{pkg}{ver_spec}")
        # For >= constraints, compare numerically
        elif ver_spec.startswith(">="):
            from packaging.version import parse as parse_version
            if parse_version(installed_version) < parse_version(ver_spec[2:]):
                to_install.append(f"{pkg}{ver_spec}")
    except PackageNotFoundError:
        # Package missing → install
        to_install.append(f"{pkg}{ver_spec}")

if to_install:
    print("Installing:", to_install)
    subprocess.run([sys.executable, "-m", "pip", "install"] + to_install, check=True)
else:
    print("All packages already satisfy version requirements.")

All packages already satisfy version requirements.

**After running cell above, restart kernel** (shortcut: click <0><0> quickly).

In [3]:
# ====================================
# ==== Downloads of NLP resources ====
# ====================================

# NLTK stopwords
import nltk
nltk.download("stopwords", quiet=True)

# spaCy English model (small)
import spacy
from spacy.cli import download as spacy_download

try:
    nlp = spacy.load("en_core_web_sm", disable=["parser", "ner"])
except OSError:
    spacy_download("en_core_web_sm")
    nlp = spacy.load("en_core_web_sm", disable=["parser", "ner"])

print("NLP resources downloaded.")

NLP resources downloaded.

In [4]:
# ===========================
# ==== utils.py imports  ====
# ===========================
import sys
from pathlib import Path

# Replace this path with the folder containing notebook and utils.py
notebook_dir = Path("/home/usuario/Documents/KeepCoding/MLOps-LLMOps/mlops-llmops-bd16/Practical")
if str(notebook_dir) not in sys.path:
    sys.path.insert(0, str(notebook_dir))

from utils import preprocess_reviews, reviews_to_dict
print("Utils imported successfully!")

Utils imported successfully!

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/usuario/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [5]:
# ===========================
# ===== Library imports =====
# ===========================

# Data processing
import pandas as pd
import numpy as np
import scipy

# Saving
import joblib, pickle, json

# Text processing
from nltk.corpus import stopwords

# ML model and pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    precision_score, recall_score, f1_score, accuracy_score,
    confusion_matrix, classification_report, ConfusionMatrixDisplay,
    roc_curve, roc_auc_score)
from sklearn.inspection import permutation_importance

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Scientific computing
from scipy.sparse import hstack

# Model tracking
import mlflow
import mlflow.sklearn

print("Imports done.")

Imports done.

# Part 1. Classification with scikit-learn and MLflow

## 1. Data exploration using scikit-learn

In this section, I briefly explore the dataset to understand its content and structure, following these steps:

1. **Loading the dataset:**

The `Sports_and_Outdoors_5.json` is loaded into a Python dictionary of dictionaries, using the function `reviews_to_dict()` from `utils.py`. Each entry of the main dictionary is an integer from 0 (first review) to n-1 (last review), for a total of n reviews. Each integer entry is a review containing the fields that can be potential features and the target (binary label). The dictionary is also saved to a json file with the prefix `dict_`.


2. **Creating a DataFrame:**

A DataFrame is created from the dataset, using the method `DataFrame.from_dict()` from Pandas, assigning the features and target to columns.

3. **Previewing the first records:**

The first rows of the DataFrame are displayed to gain an initial understanding of the data.

4. **Getting the DataFrame dimensions:**

The shape of the DataFrame is printed to show the number of rows and columns.

5. **Visualizing descriptive statistics:**

Descriptive statistics of the DataFrame are provided, including counts, means, standard deviations, quartiles, and minima and maxima. In the dataset provided, Class 1 (negative sentiment) is clearly the minority class, since the maximum value of `label` is 1 but all other quartiles are 0. In fact, only 6.5% of the data has label 1.

6. **Column names:**

The names of the columns present in the DataFrame are displayed.

**Summary:**

The code presented below serves as a starting point to explore and understand the `Sports_and_Outdoors_5.json` dataset and to perform basic statistical analysis on its numerical features and target variable.

In [6]:
# Load JSON dataset into dictionary using utils function
file = "Sports_and_Outdoors_5.json"
folder = "/home/usuario/Documents/KeepCoding/MLOps-LLMOps/mlops-llmops-bd16/Practical/"
reviews_dict = reviews_to_dict(folder, file)

Dictionary created.
Dictionary saved to: /home/usuario/Documents/KeepCoding/MLOps-LLMOps/mlops-llmops-bd16/Practical/Sports_and_Outdoors_5.json.

To load the file, use this code:

with open('/home/usuario/Documents/KeepCoding/MLOps-LLMOps/mlops-llmops-bd16/Practical/Sports_and_Outdoors_5.json', 'r') as f:
  reviews_dict = json.load(f)

In [7]:
# Convert to DataFrame
df = pd.DataFrame.from_dict(reviews_dict, orient='index')
print("Dataframe created and loaded.")

Dataframe created and loaded.

In [8]:
df.head()

   label helpful  age                                               text
0      0  [0, 0]  178  This came in on time and I am veru happy with ...
1      0  [1, 1]  902  I had a factory Glock tool that I was using fo...
2      0  [2, 2]  876  If you don't have a 3/32 punch or would like t...
3      0  [0, 0]  899  This works no better than any 3/32 punch you w...
4      0  [0, 0]  456  I purchased this thinking maybe I need a speci...

In [9]:
df.shape

(296337, 4)

In [10]:
df.describe()

               label            age
count  296337.000000  296337.000000
mean        0.146185     485.425924
std         0.353292     409.091571
min         0.000000       0.000000
25%         0.000000     198.000000
50%         0.000000     401.000000
75%         0.000000     605.000000
max         1.000000    4521.000000

## 2. Text preprocessing

In this part, I implement text preprocessing tasks in one large function located in `utils.py` to prepare the data for modeling. The steps in the function are as follows:

1. **Tokenize, lemmatize, lowercase, stop words removal:**

    Using spaCy's built-in functions, each review is tokenized (separated into words, and punctuation and extra spaces are removed), then each token is lemmatized with POS awareness, turned to lowercase, and finally stopwords are removed. The stopwords list used is based on the NLTK default but words that carry contrasting views or polar sentiment are removed from the list so they can remain in the review.

2. **Store review length for use as an additional feature:**

    The length of each review (in number of tokens) is stored to be included as an additional feature, as longer reviews often correlate with negative sentiment. This feature will later be normalized using StandardScaler.

3. **Truncate very long reviews:**

    Once the length of the review is stored, the reviews that are extremely long are truncated to a maximum number of tokens (set as a default to 512), preserving context and concluding sentiment by keeping the first and last tokens of the review and deleting the middle ones.

4. **Reconstruct processed text:**

    The processed text is put back together, appending tokens with single spaces as separators. 

5. **Inform on processing:**

    A short snippet informs on how many reviews have been processed, printing a message every 10,000 reviews.

6. **Add preprocessed review `processedText` and `reviewLength` to DataFrame:**

    The two features to be used in the model are stored as new columns in the DataFrame.

7. **Save preprocessed DataFrame to a pickle file**

    The preprocessed DataFrame is saved to a pickle file.

    To retrieve it, run: `df = pd.read_pickle(folder + "preprocessed_data.pkl")`

   
**Summary:**

The code below runs function `preprocess_reviews()` (imported from `utils.py`), which processes the text of the reviews using NLP techniques so that they can later be used for training the model.

In [11]:
# RUNNING THIS CELL STARTS THE PREPROCESSING (about 45 min)
# Uncomment below if you still want to run it

#preprocess_reviews(df)

# Save df to pickle file for later retrieval
#df.to_pickle(folder+"preprocessed_data.pkl")

In [12]:
# Retrieve preprocessed DataFrame from pickle file
df = pd.read_pickle(folder + "preprocessed_data.pkl")

In [13]:
df.head()

,label,helpful,age,text,reviewLength,processedText
0,0,"[0, 0]",178,This came in on time and I am veru happy with ...,12,come time veru happy use already make take pin...
1,0,"[1, 1]",902,I had a factory Glock tool that I was using fo...,28,factory glock tool use glock 26 27 17 since lo...
2,0,"[2, 2]",876,If you don't have a 3/32 punch or would like t...,24,not 3/32 punch would like one glock bag okay b...
3,0,"[0, 0]",899,This works no better than any 3/32 punch you w...,17,work no well 3/32 punch would find hardware st...
4,0,"[0, 0]",456,I purchased this thinking maybe I need a speci...,29,purchase thinking maybe need special tool easi...

## 3. Model training with scikit-learn

Here I will use scikit-learn to train and validate a classification model for the preprocessed data. I will follow these steps:

1. **Dataset Splitting:**

    The preprocessed dataset is split into training sets X_train_full_raw and y_train_full, and test sets X_test_raw and y_test, using the `train_test_split` function. Only the relevant features are kept, and the split is applied stratifying by `label` due to severe imbalance between the two classes.

2. **Preparing the Test Set:**

    The target set y_test is saved to a CSV file called 'test-target.csv'. The features test set is saved to another CSV file called 'test.csv'.

3. **Training Set Splitting:**

    The training set is further split into training subsets X_train_raw and y_train, and validation subsets X_val_raw and y_val using `train_test_split` again.

4. **Model Configuration:**

    A classification model is configured using the selected model (Logistic Regression) with the chosen parameters.

5. **Preprocessing and training pipeline:**

    A `pipeline` is configured that includes:

* **TF-IDF Vectorization, `reviewLength`Scaling, and combination of both features:**

    A Bag of Words representation, weighted by inverse frequency using TF‑IDF vectorization, is configured, using max_features = 10,000 and n-grams in range (1,3). The bigrams and trigrams will enable the model to distinguish between cases such as "good", "really good" or "really not good".

    The review length field is standardized using StandardScaler, to enable the model to better adjust the weights.

    A `ColumnTransformer` is used to combine the *TF-IDF features* and the *scaled review length* into a single feature matrix which will be fed into the model, allowing the model to use both text content and review length simultaneously.

* **Model Training with Hyperparameter Tuning:**

    `GridSearchCV` is configured to tune hyperparameters using 5-fold cross-validation, selecting the parameters yielding the best F1 score. The full pipeline is displayed in a diagram. Finally, the model is fitted on the X_train subset.

5. **Performance on the validation set:**

    The model is evaluated using the validation set. If not successful, parameters can be modified and the pipeline restarted.

**Summary:**  

The following lines of code thus represent the process of data preparation, model configuration, and training of a classification model using *Logistic Regression* in scikit-learn.

In [14]:
# 1. Dataset Splitting
X_train_full, X_test, y_train_full, y_test = train_test_split(
    df[['processedText','reviewLength']],
    df['label'],
    test_size=0.2,
    stratify=df['label'],
    random_state=17
)

In [15]:
# 2. Preparing the test set
y_test.to_csv(folder+'test-target.csv', index=False)
X_test.to_csv(folder+'test.csv', index=False)

In [16]:
# 3. Training set Splitting
X_train, X_val, y_train, y_val = train_test_split(
    X_train_full,
    y_train_full,
    test_size=0.2,
    stratify=y_train_full,
    random_state=17
)

In [17]:
# TF-IDF Vectorization (with trigrams and 10,000 max features)
cv = TfidfVectorizer(
    ngram_range=(1,3),  # going up to trigrams
    min_df=10,      # ignore tokens that appear less than this number of times (attributed to noise or spelling errors)
    max_df=0.95,       # ignore very high frequency tokens
    max_features=10000 
)

X_train_cv = cv.fit_transform(X_train['processedText'])  # Fit-transform on training data
X_val_cv = cv.transform(X_val['processedText'])
X_test_cv = cv.transform(X_test['processedText'])        # Just transform on testing and validation data

In [18]:
# Standardize the feature 'reviewLength'
# (necessary for LogisticRegression model)

scaler = StandardScaler()

X_train_len = scaler.fit_transform(X_train[['reviewLength']])  # Fit-transform on training data
X_val_len = scaler.transform(X_val[['reviewLength']])        
X_test_len = scaler.transform(X_test[['reviewLength']])        # Just transform on testing and validation data

In [45]:
# 5. Define preprocessing and training pipeline

scoring='precision'
C_params=[5]

# Column transformer for combining features
preprocessor = ColumnTransformer(
    transformers=[
        ('tfidf', TfidfVectorizer(ngram_range=(1,3), max_features=10000, min_df=10, max_df=0.95), 'processedText'),
        ('length', StandardScaler(), ['reviewLength'])
    ]
)

# Pipeline with Logistic Regression
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(max_iter=1000, class_weight='balanced'))
])

# Define hyperparameter grid for tuning
param_grid = {
    'classifier__C': C_params,        # Regularization strength
    'classifier__solver': ['lbfgs']   # Fast & stable for large datasets, L2-compatible
}

# Setup GridSearchCV
grid_search = GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    scoring=scoring,            # Best F1 score selects best parameter (unbalanced classes)
    cv=5,                    # 5-fold cross-validation for tuning
    n_jobs=-1,               # Use all cores
    verbose=1
)

In [46]:
model

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('tfidf',
                                                  TfidfVectorizer(max_df=0.95,
                                                                  max_features=10000,
                                                                  min_df=10,
                                                                  ngram_range=(1,
                                                                               3)),
                                                  'processedText'),
                                                 ('length', StandardScaler(),
                                                  ['reviewLength'])])),
                ('classifier',
                 LogisticRegression(class_weight='balanced', max_iter=1000))])

In [47]:
# Training of the model
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 1 candidates, totalling 5 fits

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('tfidf',
                                                                         TfidfVectorizer(max_df=0.95,
                                                                                         max_features=10000,
                                                                                         min_df=10,
                                                                                         ngram_range=(1,
                                                                                                      3)),
                                                                         'processedText'),
                                                                        ('length',
                                                                         StandardScaler(),
                                                                         ['reviewLength'])])),
                                       ('classifier',
                                        LogisticRegression(class_weight='balanced',
                                                           max_iter=1000))]),
             n_jobs=-1,
             param_grid={'classifier__C': [5], 'classifier__solver': ['lbfgs']},
             scoring='precision', verbose=1)

In [48]:
# Best model and hyperparameters
best_model = grid_search.best_estimator_
print("Best hyperparameters:", grid_search.best_params_)

Best hyperparameters: {'classifier__C': 5, 'classifier__solver': 'lbfgs'}

In [49]:
# 6. Performance evaluation on the validation set
y_val_pred = best_model.predict(X_val)

print("Validation Metrics:")
print(classification_report(y_val, y_val_pred, digits=4))

Validation Metrics:
              precision    recall  f1-score   support

           0     0.9617    0.8475    0.9010     40483
           1     0.4740    0.8026    0.5960      6931

    accuracy                         0.8409     47414
   macro avg     0.7178    0.8251    0.7485     47414
weighted avg     0.8904    0.8409    0.8564     47414

## 4. Model Evaluation and Retrieval of Parameters

In this section, the previously trained model is evaluated and some standard performance indicators (such as precision and recall) and configuration parameters are retrieved and displayed. The following is a brief description of the steps followed in the code.

1. **Performance evaluation on the training set:**

    The model's performance on the training data is calculated and printed.

2. **Performance evaluation on the test set:**

    The model's performance on the test set is calculated and printed.

3. **Retrieval and storage of the model's parameters and metrics:**

    The model parameters are obtained using the `get_params` function. This provides detailed information about the model's configuration.

**Summary:**

The code below thus focuses on evaluating the model's performance on the training and test sets. It also retrieves and stores detailed information about the model's configuration.

In [50]:
# 1. Performance evaluation on the training set
y_train_pred = best_model.predict(X_train)

accuracy_train  = accuracy_score(y_train, y_train_pred)
precision_train = precision_score(y_train, y_train_pred)
recall_train    = recall_score(y_train, y_train_pred)
f1_train        = f1_score(y_train, y_train_pred)

print("Train Metrics:")
print(classification_report(y_train, y_train_pred, digits=4))

Train Metrics:
              precision    recall  f1-score   support

           0     0.9772    0.8656    0.9181    161930
           1     0.5292    0.8822    0.6616     27725

    accuracy                         0.8681    189655
   macro avg     0.7532    0.8739    0.7898    189655
weighted avg     0.9117    0.8681    0.8806    189655

In [51]:
# 2. Performance evaluation on the test set
y_test_pred = best_model.predict(X_test)

accuracy_test  = accuracy_score(y_test, y_test_pred)
precision_test = precision_score(y_test, y_test_pred)
recall_test    = recall_score(y_test, y_test_pred)
f1_test        = f1_score(y_test, y_test_pred)

print("Test Metrics:")
print(classification_report(y_test, y_test_pred, digits=4))

Test Metrics:
              precision    recall  f1-score   support

           0     0.9627    0.8534    0.9048     50604
           1     0.4852    0.8068    0.6060      8664

    accuracy                         0.8466     59268
   macro avg     0.7239    0.8301    0.7554     59268
weighted avg     0.8929    0.8466    0.8611     59268

In [52]:
# 3. Retrieval and storage of the model's best parameters and metrics

# Parameters
best_params = grid_search.best_params_          # Only tuned parameters
full_params = best_model.get_params()           # Full pipeline configuration

# Metrics
metrics = {
    "train_accuracy":  accuracy_score(y_train, y_train_pred),
    "train_precision": precision_score(y_train, y_train_pred),
    "train_recall":    recall_score(y_train, y_train_pred),
    "train_f1":        f1_score(y_train, y_train_pred),

    "test_accuracy":   accuracy_score(y_test, y_test_pred),
    "test_precision":  precision_score(y_test, y_test_pred),
    "test_recall":     recall_score(y_test, y_test_pred),
    "test_f1":         f1_score(y_test, y_test_pred),
}

In [53]:
# Save trained model and metrics to files

joblib.dump(best_model, folder+'model.pkl')    # Trained model

with open(folder+'metrics.json', 'w') as f:    # Metrics
    json.dump(metrics, f)

## 5. Logging Metrics with MLflow

MLflow will be used to record metrics and hyperparameters from training, making it easier to manage and compare experiments and models from a centralized location.

1. **Configuration of the MLflow Server:**

    The MLflow server is initialized **from the terminal** using the command **mlflow server --host 127.0.0.1 --port 8080**, with the backend configuration and the artifacts directory. (This could also be done from a Docker Compose file.) 

2. **Configuration of each experiment:**

    The URI (Unifrom Resource Identifier) and the name of the experiment are set using `mlflow.set_tracking_uri`and `mlflow.set_experiment`, respectively.

3. **Logging of model and metrics:**

    A run of MLflow is setup with `mlflow.start_run()` and the metrics and trained model are logged using `mlflow.log_metric` and `mlflow.sklearn.log_model`.

4. **Registration of the model in the model log:**

    Using `mlflow.register_model`, the model is logged into the Registry of MLflow Models.

5. **Version management and deployment:**

    * Information about the model versions is retrieved, and the transition of versions and stages is carried out using specific functions from the MLflow API. 
    
    * The process waits until the transition to the "Staging" stage is complete before updating the model's description with `client.update_model_version`.

In [ ]:
# LOADING MODEL AND METRICS IF NEEDED
# After switching kernels to be able to work with MLflow, 
# uncomment the following lines and run this cell:

#folder = "/home/usuario/Documents/KeepCoding/MLOps-LLMOps/mlops-llmops-bd16/Practical/"

#df = pd.read_pickle(folder+"preprocessed_data.pkl")
#best_model = joblib.load(folder+"model.pkl")

#with open(folder+"metrics.json", "r") as f:
    #metrics = json.load(f)

In [54]:
# 2. Configuration of an experiment

# Notebook must point to the same tracking URI as the server
mlflow.set_tracking_uri("http://127.0.0.1:8080")  # must match MLflow server

# Set experiment name
mlflow.set_experiment('SentimentClassification_LogisticRegression')

# 3. Logging of model and metrics

with mlflow.start_run(run_name='KC-BD16'):

    # Log train metrics
    mlflow.log_metric("f1_train", metrics["train_f1"])
    mlflow.log_metric("recall_train", metrics["train_recall"])
    mlflow.log_metric("precision_train", metrics["train_precision"])
    mlflow.log_metric("accuracy_train", metrics["train_accuracy"])
    mlflow.log_metric("f1_test", metrics["test_f1"])
    mlflow.log_metric("recall_test", metrics["test_recall"])
    mlflow.log_metric("precision_test", metrics["test_precision"])
    mlflow.log_metric("accuracy_test", metrics["test_accuracy"])
    
    # Log hyperparameters
    mlflow.log_params(grid_search.best_params_)

    # Log full pipeline configuration
    mlflow.log_params({
        f"param_{k}": v
        for k, v in best_model.get_params().items()
    })

    # Log trained model
    mlflow.sklearn.log_model(best_model, "classifier")

2026/03/03 02:48:19 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/03/03 02:48:20 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run KC-BD16 at: http://127.0.0.1:8080/#/experiments/2/runs/9d5042c391834d6f9d24b193ddb2b46b
🧪 View experiment at: http://127.0.0.1:8080/#/experiments/2

In [55]:
# 4. Registration of model
model_name = 'SentimentClassifier'
model_mlflow = mlflow.pyfunc.load_model(f'models:/{model_name}/Production')

Downloading artifacts: 100%|██████████| 5/5 [00:00<00:00, 72.64it/s]

## Generar .py de funciones y main con al menos dos argumentos de entrada.

In [56]:
!pip install "mlflow>=3.10.0" langchain langchain-google-genai google-generativeai python-dotenv

Requirement already satisfied: mlflow>=3.10.0 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (3.10.0)
Collecting langchain
  Using cached langchain-1.2.10-py3-none-any.whl.metadata (5.7 kB)
Collecting langchain-google-genai
  Using cached langchain_google_genai-4.2.1-py3-none-any.whl.metadata (2.7 kB)
Collecting google-generativeai
  Using cached google_generativeai-0.8.6-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: python-dotenv in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (1.2.2)
Requirement already satisfied: mlflow-skinny==3.10.0 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from mlflow>=3.10.0) (3.10.0)
Requirement already satisfied: mlflow-tracing==3.10.0 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from mlflow>=3.10.0) (3.10.0)
Requirement already satisfied: Flask-CORS<7 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from mlflow>=3.10.0) (6.0.2)
Requirement already satisfied: Flask<4 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from mlflow>=3.10.0) (3.1.3)
Requirement already satisfied: alembic!=1.10.0,<2 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from mlflow>=3.10.0) (1.18.4)
Requirement already satisfied: cryptography<47,>=43.0.0 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from mlflow>=3.10.0) (46.0.5)
Requirement already satisfied: docker<8,>=4.0.0 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from mlflow>=3.10.0) (7.1.0)
Requirement already satisfied: graphene<4 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from mlflow>=3.10.0) (3.4.3)
Requirement already satisfied: gunicorn<26 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from mlflow>=3.10.0) (25.1.0)
Requirement already satisfied: huey<3,>=2.5.4 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from mlflow>=3.10.0) (2.6.0)
Requirement already satisfied: matplotlib<4 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from mlflow>=3.10.0) (3.10.8)
Requirement already satisfied: numpy<3 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from mlflow>=3.10.0) (2.4.2)
Requirement already satisfied: pandas<3 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from mlflow>=3.10.0) (2.3.3)
Requirement already satisfied: pyarrow<24,>=4.0.0 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from mlflow>=3.10.0) (23.0.1)
Requirement already satisfied: scikit-learn<2 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from mlflow>=3.10.0) (1.8.0)
Requirement already satisfied: scipy<2 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from mlflow>=3.10.0) (1.17.1)
Requirement already satisfied: skops<1 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from mlflow>=3.10.0) (0.13.0)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from mlflow>=3.10.0) (2.0.48)
Requirement already satisfied: cachetools<8,>=5.0.0 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from mlflow-skinny==3.10.0->mlflow>=3.10.0) (7.0.2)
Requirement already satisfied: click<9,>=7.0 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from mlflow-skinny==3.10.0->mlflow>=3.10.0) (8.3.1)
Requirement already satisfied: cloudpickle<4 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from mlflow-skinny==3.10.0->mlflow>=3.10.0) (3.1.2)
Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from mlflow-skinny==3.10.0->mlflow>=3.10.0) (0.95.0)
Requirement already satisfied: fastapi<1 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from mlflow-skinny==3.10.0->mlflow>=3.10.0) (0.135.1)
Requirement already satisfied: gitpython<4,>=3.1.9 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from mlflow-skinny==3.10.0->mlflow>=3.10.0) (3.1.46)
Requirement already satisfied: importlib_metadata!=4.7.0,<9,>=3.7.0 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from mlflow-skinny==3.10.0->mlflow>=3.10.0) (8.7.1)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from mlflow-skinny==3.10.0->mlflow>=3.10.0) (1.39.1)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from mlflow-skinny==3.10.0->mlflow>=3.10.0) (1.39.1)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from mlflow-skinny==3.10.0->mlflow>=3.10.0) (1.39.1)
Requirement already satisfied: packaging<27 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from mlflow-skinny==3.10.0->mlflow>=3.10.0) (25.0)
Requirement already satisfied: protobuf<7,>=3.12.0 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from mlflow-skinny==3.10.0->mlflow>=3.10.0) (6.33.5)
Requirement already satisfied: pydantic<3,>=2.0.0 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from mlflow-skinny==3.10.0->mlflow>=3.10.0) (2.12.5)
Requirement already satisfied: pyyaml<7,>=5.1 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from mlflow-skinny==3.10.0->mlflow>=3.10.0) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from mlflow-skinny==3.10.0->mlflow>=3.10.0) (2.32.5)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from mlflow-skinny==3.10.0->mlflow>=3.10.0) (0.5.5)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from mlflow-skinny==3.10.0->mlflow>=3.10.0) (4.15.0)
Requirement already satisfied: uvicorn<1 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from mlflow-skinny==3.10.0->mlflow>=3.10.0) (0.41.0)
Requirement already satisfied: Mako in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from alembic!=1.10.0,<2->mlflow>=3.10.0) (1.3.10)
Requirement already satisfied: cffi>=2.0.0 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from cryptography<47,>=43.0.0->mlflow>=3.10.0) (2.0.0)
Requirement already satisfied: google-auth~=2.0 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.10.0->mlflow>=3.10.0) (2.48.0)
Requirement already satisfied: urllib3>=1.26.0 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from docker<8,>=4.0.0->mlflow>=3.10.0) (2.6.3)
Requirement already satisfied: starlette>=0.46.0 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from fastapi<1->mlflow-skinny==3.10.0->mlflow>=3.10.0) (0.52.1)
Requirement already satisfied: typing-inspection>=0.4.2 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from fastapi<1->mlflow-skinny==3.10.0->mlflow>=3.10.0) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from fastapi<1->mlflow-skinny==3.10.0->mlflow>=3.10.0) (0.0.4)
Requirement already satisfied: blinker>=1.9.0 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from Flask<4->mlflow>=3.10.0) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from Flask<4->mlflow>=3.10.0) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from Flask<4->mlflow>=3.10.0) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from Flask<4->mlflow>=3.10.0) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from Flask<4->mlflow>=3.10.0) (3.1.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.10.0->mlflow>=3.10.0) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.10.0->mlflow>=3.10.0) (5.0.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.10.0->mlflow>=3.10.0) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.10.0->mlflow>=3.10.0) (4.9.1)
Requirement already satisfied: graphql-core<3.3,>=3.1 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from graphene<4->mlflow>=3.10.0) (3.2.7)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from graphene<4->mlflow>=3.10.0) (3.2.0)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from graphene<4->mlflow>=3.10.0) (2.9.0.post0)
Requirement already satisfied: zipp>=3.20 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from importlib_metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==3.10.0->mlflow>=3.10.0) (3.23.0)
Requirement already satisfied: contourpy>=1.0.1 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from matplotlib<4->mlflow>=3.10.0) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from matplotlib<4->mlflow>=3.10.0) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from matplotlib<4->mlflow>=3.10.0) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from matplotlib<4->mlflow>=3.10.0) (1.4.9)
Requirement already satisfied: pillow>=8 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from matplotlib<4->mlflow>=3.10.0) (12.1.1)
Requirement already satisfied: pyparsing>=3 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from matplotlib<4->mlflow>=3.10.0) (3.3.2)
Requirement already satisfied: opentelemetry-semantic-conventions==0.60b1 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.10.0->mlflow>=3.10.0) (0.60b1)
Requirement already satisfied: pytz>=2020.1 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from pandas<3->mlflow>=3.10.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from pandas<3->mlflow>=3.10.0) (2025.3)
Requirement already satisfied: annotated-types>=0.6.0 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.10.0->mlflow>=3.10.0) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.10.0->mlflow>=3.10.0) (2.41.5)
Requirement already satisfied: six>=1.5 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow>=3.10.0) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.10.0->mlflow>=3.10.0) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.10.0->mlflow>=3.10.0) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.10.0->mlflow>=3.10.0) (2026.2.25)
Requirement already satisfied: pyasn1>=0.1.3 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from rsa<5,>=3.1.4->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.10.0->mlflow>=3.10.0) (0.6.2)
Requirement already satisfied: joblib>=1.3.0 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from scikit-learn<2->mlflow>=3.10.0) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from scikit-learn<2->mlflow>=3.10.0) (3.6.0)
Requirement already satisfied: prettytable>=3.9 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from skops<1->mlflow>=3.10.0) (3.17.0)
Requirement already satisfied: greenlet>=1 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from sqlalchemy<3,>=1.4.0->mlflow>=3.10.0) (3.3.2)
Requirement already satisfied: h11>=0.8 in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from uvicorn<1->mlflow-skinny==3.10.0->mlflow>=3.10.0) (0.16.0)
Collecting langchain-core<2.0.0,>=1.2.10 (from langchain)
  Downloading langchain_core-1.2.17-py3-none-any.whl.metadata (4.4 kB)
Collecting langgraph<1.1.0,>=1.0.8 (from langchain)
  Using cached langgraph-1.0.10-py3-none-any.whl.metadata (7.4 kB)
Collecting jsonpatch<2.0.0,>=1.33.0 (from langchain-core<2.0.0,>=1.2.10->langchain)
  Downloading jsonpatch-1.33-py2.py3-none-any.whl.metadata (3.0 kB)
Collecting langsmith<1.0.0,>=0.3.45 (from langchain-core<2.0.0,>=1.2.10->langchain)
  Downloading langsmith-0.7.10-py3-none-any.whl.metadata (15 kB)
Collecting tenacity!=8.4.0,<10.0.0,>=8.1.0 (from langchain-core<2.0.0,>=1.2.10->langchain)
  Downloading tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)
Collecting uuid-utils<1.0,>=0.12.0 (from langchain-core<2.0.0,>=1.2.10->langchain)
  Using cached uuid_utils-0.14.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.8 kB)
Collecting jsonpointer>=1.9 (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.10->langchain)
  Using cached jsonpointer-3.0.0-py2.py3-none-any.whl.metadata (2.3 kB)
Collecting langgraph-checkpoint<5.0.0,>=2.1.0 (from langgraph<1.1.0,>=1.0.8->langchain)
  Using cached langgraph_checkpoint-4.0.1-py3-none-any.whl.metadata (4.9 kB)
Collecting langgraph-prebuilt<1.1.0,>=1.0.8 (from langgraph<1.1.0,>=1.0.8->langchain)
  Using cached langgraph_prebuilt-1.0.8-py3-none-any.whl.metadata (5.2 kB)
Collecting langgraph-sdk<0.4.0,>=0.3.0 (from langgraph<1.1.0,>=1.0.8->langchain)
  Using cached langgraph_sdk-0.3.9-py3-none-any.whl.metadata (1.6 kB)
Collecting xxhash>=3.5.0 (from langgraph<1.1.0,>=1.0.8->langchain)
  Downloading xxhash-3.6.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Collecting ormsgpack>=1.12.0 (from langgraph-checkpoint<5.0.0,>=2.1.0->langgraph<1.1.0,>=1.0.8->langchain)
  Downloading ormsgpack-1.12.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.2 kB)
Collecting httpx>=0.25.2 (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.8->langchain)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting orjson>=3.11.5 (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.8->langchain)
  Downloading orjson-3.11.7-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (41 kB)
Collecting requests-toolbelt>=1.0.0 (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.10->langchain)
  Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
Collecting zstandard>=0.23.0 (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.10->langchain)
  Downloading zstandard-0.25.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (3.3 kB)
Requirement already satisfied: anyio in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.8->langchain) (4.12.1)
Collecting httpcore==1.* (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.8->langchain)
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting filetype<2.0.0,>=1.2.0 (from langchain-google-genai)
  Using cached filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting google-genai<2.0.0,>=1.56.0 (from langchain-google-genai)
  Using cached google_genai-1.65.0-py3-none-any.whl.metadata (51 kB)
Collecting websockets<17.0,>=13.0.0 (from google-genai<2.0.0,>=1.56.0->langchain-google-genai)
  Downloading websockets-16.0-cp311-cp311-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (6.8 kB)
Collecting distro<2,>=1.7.0 (from google-genai<2.0.0,>=1.56.0->langchain-google-genai)
  Downloading distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
Collecting sniffio (from google-genai<2.0.0,>=1.56.0->langchain-google-genai)
  Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting google-ai-generativelanguage==0.6.15 (from google-generativeai)
  Using cached google_ai_generativelanguage-0.6.15-py3-none-any.whl.metadata (5.7 kB)
Collecting google-api-core (from google-generativeai)
  Using cached google_api_core-2.30.0-py3-none-any.whl.metadata (3.1 kB)
Collecting google-api-python-client (from google-generativeai)
  Downloading google_api_python_client-2.191.0-py3-none-any.whl.metadata (7.0 kB)
Requirement already satisfied: tqdm in /home/usuario/anaconda3/envs/bd16-mlops-v2/lib/python3.11/site-packages (from google-generativeai) (4.67.3)
Collecting proto-plus<2.0.0dev,>=1.22.3 (from google-ai-generativelanguage==0.6.15->google-generativeai)
  Using cached proto_plus-1.27.1-py3-none-any.whl.metadata (2.2 kB)
Collecting protobuf<7,>=3.12.0 (from mlflow-skinny==3.10.0->mlflow>=3.10.0)
  Using cached protobuf-5.29.6-cp38-abi3-manylinux2014_x86_64.whl.metadata (592 bytes)
Collecting googleapis-common-protos<2.0.0,>=1.56.3 (from google-api-core->google-generativeai)
  Using cached googleapis_common_protos-1.72.0-py3-none-any.whl.metadata (9.4 kB)
Collecting grpcio<2.0.0,>=1.33.2 (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai)
  Downloading grpcio-1.78.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (3.8 kB)
Collecting grpcio-status<2.0.0,>=1.33.2 (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai)
  Using cached grpcio_status-1.78.0-py3-none-any.whl.metadata (1.3 kB)
INFO: pip is looking at multiple versions of grpcio-status to determine which version is compatible with other requirements. This could take a while.
  Using cached grpcio_status-1.76.0-py3-none-any.whl.metadata (1.1 kB)
  Using cached grpcio_status-1.75.1-py3-none-any.whl.metadata (1.1 kB)

In [57]:
import os
import mlflow
from dotenv import load_dotenv

In [59]:
load_dotenv()

# Configure tracking URI
MLFLOW_TRACKING_URI = "http://127.0.0.1:8080"
mlflow.set_tracking_uri(MLFLOW_TRACKING_URI)

print(f"MLflow Tracking URI: {mlflow.get_tracking_uri()}")

# Configure the API key for Google
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")

if not GOOGLE_API_KEY:
    raise ValueError("Configure GOOGLE_API_KEY in your .env file")

print("API key correctly configured.")

MLflow Tracking URI: http://127.0.0.1:8080
API key correctly configured.

In [ ]:
# HERE WE ARE USING SPECIFICALLY GOOGLE MODELS

import google.generativeai as genai

# Mobilize auto-tracking for Gemini
mlflow.gemini.autolog()

# Configure the experiment
mlflow.set_experiment("Gemini_Direct_Tracking")

# Configure Google SDK
experiment = genai.configure(api_key=GOOGLE_API_KEY)

print("MLflow Gemini autolog enabled.")
print(f"Experiment: {experiment}")

2026/03/03 19:57:41 INFO mlflow.tracking.fluent: Experiment with name 'Gemini_Direct_Tracking' does not exist. Creating a new experiment.

MLflow Gemini autolog enabled.
Experiment: <Experiment: artifact_location='mlflow-artifacts:/3', creation_time=1772564261753, experiment_id='3', last_update_time=1772564261753, lifecycle_stage='active', name='Gemini_Direct_Tracking', tags={}, workspace='default'>

In [61]:
model = genai.GenerativeModel("gemini-2.5-flash")

# Start with a simple call - MLflow will automatically capture the trace
response = model.generate_content("What is MLflow and what is it used for? Answer in 2-3 sentences.")

print("Answer: ")
print(response.text)

Answer:
MLflow is an open-source platform designed to manage the entire machine learning (ML) lifecycle. It provides tools for tracking experiments (parameters, metrics, artifacts), packaging reproducible ML code into "projects," managing and versioning models through a "registry," and deploying them to various serving environments. Its primary use is to streamline ML development, ensure reproducibility, and facilitate MLOps practices.

Trace(trace_id=tr-39258144163a9874f89075cefc265050)

In [63]:
# Example of a multi-turn chat
chat = model.start_chat(history=[])

# First question
response1 = chat.send_message("In one sentence, explain what Docker is.")
print("1st turn: ", response1.text)

# Second question
response2 = chat.send_message("And Kubernetes? Also in one sentence.")
print("2nd turn: ", response2.text)

1st turn:  Docker is a platform that packages applications and all their dependencies into standardized, isolated units called containers, ensuring they run consistently across any environment.
2nd turn:  Kubernetes is an open-source container orchestration platform that automates the deployment, scaling, and management of containerized applications across a cluster of machines.

[Trace(trace_id=tr-4e406f2f261be919410136036f4f8521), Trace(trace_id=tr-e376f4893680dfb35b52dfa25fc8675e)]

In [64]:
# Third question
response3 = chat.send_message("Explain Docker in a very detailed and technical manner.")
print("3rd turn: ", response3.text)

3rd turn:  Docker is an open-source platform designed to facilitate the development, packaging, and deployment of applications within isolated, standardized environments called **containers**, utilizing Linux kernel features like **namespaces** and **cgroups** to provide lightweight virtualization.

Here's a breakdown of its technical intricacies:

1.  **Core Abstractions:**
    *   **Docker Images:** These are read-only, immutable templates that contain an application, its dependencies, runtime, and the necessary configurations. Images are built from a `Dockerfile`, which is a plain-text file containing a series of instructions (`FROM`, `RUN`, `COPY`, `EXPOSE`, `CMD`, `ENTRYPOINT`) that define the environment layer by layer. Images are constructed using a **Union File System (UFS)** (e.g., OverlayFS, AUFS), where each instruction in the Dockerfile creates a new, immutable read-only layer. This layered architecture enables efficient storage, caching, and distribution, as common base layers can be shared across multiple images.
    *   **Docker Containers:** These are runnable instances of a Docker image. When a container starts, a thin, writable layer is added on top of the image's read-only layers. All changes made by the running application within the container (e.g., creating files, modifying existing ones) are written to this top layer, preserving the immutability of the underlying image layers. Containers are isolated processes running on the host OS kernel, making them much more lightweight and resource-efficient than traditional Virtual Machines (VMs) which require their own full guest OS and hypervisor.

2.  **Underlying Linux Kernel Technologies:**
    *   **Namespaces:** Docker leverages various Linux namespaces to provide isolation. Each container typically gets:
        *   **PID namespace:** Isolates process IDs, so a process inside a container sees PID 1 as its own init process.
        *   **NET namespace:** Provides a private network stack, including its own network interfaces, IP addresses, routing tables, and firewall rules.
        *   **MNT namespace:** Isolates mount points, giving the container its own root filesystem view (`/`).
        *   **UTS namespace:** Isolates hostname and NIS domain name.
        *   **IPC namespace:** Isolates inter-process communication resources.
        *   **USER namespace (less commonly default, but possible):** Isolates user and group IDs for enhanced security.
    *   **Control Groups (cgroups):** Docker uses cgroups to allocate and limit resources (CPU, memory, I/O, network bandwidth) for each container. This prevents a single container from monopolizing host resources and ensures fair resource distribution among running containers.
    *   **Seccomp (Secure Computing Mode):** Filters system calls (`syscalls`) made by processes within a container, reducing the attack surface by preventing access to unnecessary kernel features.
    *   **AppArmor/SELinux:** While not strictly Docker-specific, these Mandatory Access Control (MAC) systems can be integrated with Docker to provide an additional layer of security by defining policies for what resources a container can access.

3.  **Docker Engine Architecture:**
    *   **Docker Daemon (`dockerd`):** This is the persistent background service (server) that runs on the host machine. It listens for Docker API requests and manages Docker objects such as images, containers, networks, and volumes. Its responsibilities include building images, running containers, managing storage, and configuring networks.
    *   **Docker Client (`docker CLI`):** This is the command-line interface (CLI) tool that users interact with. It communicates with the Docker daemon via a REST API (typically over a Unix socket or a network interface) to execute commands like `docker build`, `docker run`, `docker pull`, etc.
    *   **REST API:** The standard interface through which the Docker client, or any other program, can interact with and control the Docker daemon.

4.  **Networking & Storage:**
    *   **Networking:** Docker provides various networking options. By default, containers connect to a virtual bridge network (`docker0`), allowing them to communicate with each other and the host, often through Network Address Translation (NAT) for outbound internet access. User-defined bridge networks, host-mode networking (container shares host's network stack), and overlay networks (for multi-host communication with tools like Docker Swarm or Kubernetes) offer more sophisticated configurations.
    *   **Persistent Storage:** Since the writable layer of a container is ephemeral, Docker offers mechanisms for persistent data storage:
        *   **Volumes:** Docker-managed storage areas that are independent of the container's lifecycle. They are typically stored in a part of the host filesystem managed by Docker.
        *   **Bind Mounts:** Allow mounting any directory or file from the host machine directly into a container, giving the container direct access to host data.
        *   **`tmpfs` Mounts:** Store data in the host's memory, suitable for very temporary or sensitive non-persistent data.

In essence, Docker abstracts the underlying infrastructure, providing a consistent and isolated environment for applications across diverse computing environments, from development machines to production servers, by leveraging advanced Linux kernel features for lightweight virtualization and resource management.

Trace(trace_id=tr-a3c8886c4ac5d9ee46ed49a944848d15)

In [65]:
# Fourth question
response4 = chat.send_message("In one setence, compare how prompt_token_count, candidates_token_count and total_token_count are computed in each prompt.")
print("4th turn: ", response4.text)

4th turn:  For each prompt, `prompt_token_count` tracks the tokens in the *input query*, `candidates_token_count` tallies the tokens in the *model's generated response*, and `total_token_count` is their aggregate sum.

Trace(trace_id=tr-59e3f59e754cd55a91738872221419d4)

In [ ]:
# New experiment, with TRACING using the LANGCHAIN LIBRARY.
# LangChain is essentially a layer that allows us to 
# always use the same syntax in all our calls, 
# regardless of the selected model.


from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.messages import HumanMessage, SystemMessage

# Enable auto-tracing for LangChain

mlflow.set_experiment("LangChain_Gemini_Tracing")

print("MLflow LangChain autolog enabled.")
print(f"Experiment: LancChain_Gemini_Tracing")

2026/03/04 10:01:51 INFO mlflow.tracking.fluent: Experiment with name 'LangChain_Gemini_Tracing' does not exist. Creating a new experiment.

MLflow LangChain autolog enabled.
Experiment: LancChain_Gemini_Tracing

In [ ]:
# This script selects the model, temperature, etc.
# Just modify this script as needed.

llm = ChatGoogleGenerativeAI(
    model = "gemini-2.5-flash-lite",
    google_api_key = GOOGLE_API_KEY,
    temperature = 0.7,
    max_tokens = 1024
)

print("LangChain Model initialized.")

LangChain Model initialized.

In [ ]:
# We make a simple call, and the trace is captured automatically
#   SystemMessage defines the role (behavior) we want the model to have
#   HumanMessage is the actual prompt

messages = [
    SystemMessage(content="You are an expert in MLOps."),
    HumanMessage(content="What is 'experiment tracking' in ML?")
]

response = llm.invoke(messages)

print("Response:")
print(response.content)

## Chat Prompt Templates

Chat Prompt Templates are really the base that is used today, as they help to obtain a result in the expected structure.

It can be useful to see what system prompts (roles) are used in different Generative AI models. 
A search such as "openai prompt leaks" can yield interesting results and give ideas on how to better specify the system role and thus get results that are better aligned with one's goals.

In [70]:
# Using a prompt template
template = ChatPromptTemplate.from_messages([
    ("system", "You are an expert in {topic}. Respond in a {style} manner."),
    ("human", "{question}")
])

# We create the chain prompt -> LLM -> Parser 
chain = template | llm | StrOutputParser()
print("Chain created: PromptTemplate -> LLM -> StrOutputParser")

Chain created: PromptTemplate -> LLM -> StrOutputParser

In [71]:
# Now we run the chain (MLflow is still tracing each component)

result = chain.invoke({      # chain.invoke() makes the call (similar to LLM.invoke() but with a chain)
    "topic": "kubernetes",
    "style": "concise and technical",
    "question": "What are the main components of a cluster?"
})

print("Response from the Chain:")
print(result)

Response from the Chain:
A Kubernetes cluster consists of two primary types of nodes:

*   **Control Plane Nodes:** These nodes manage the cluster's state and desired configuration. Key components include:
    *   **kube-apiserver:** Exposes the Kubernetes API.
    *   **etcd:** Consistent and highly-available key-value store used as Kubernetes' backing store for all cluster data.
    *   **kube-scheduler:** Watches for newly created Pods with no assigned node and selects a node for them to run on.
    *   **kube-controller-manager:** Runs controller processes that regulate the cluster's state.
    *   **cloud-controller-manager (optional):** Embeds cloud-specific control logic.

*   **Worker Nodes:** These nodes run the actual applications (Pods). Key components include:
    *   **kubelet:** An agent that runs on each node and ensures that containers are running in a Pod as described in the PodSpec.
    *   **kube-proxy:** A network proxy that runs on each node, maintaining network rules and enabling network communication to Pods from network sessions inside or outside of the cluster.
    *   **Container Runtime:** Software responsible for running containers (e.g., Docker, containerd, CRI-O).

Trace(trace_id=tr-06ab298c264eb390e3e01cf190c5d91e)

In [ ]:
# Diferent prompt versions for comparison purposes
prompt_versions = [
    {
        "name": "basic",
        "system": "You are a helpful assistant.",
        "user": "What is Docker?"
    },
    {
        "name": "expert",
        "system": "You are a DevOps expert with 10 years experience. Respond in a technical but accessible manner.",
        "user": "What is Docker?"
    },
    {
        "name": "structured",
        "system": "You are a DevOps expert. Respond in this format: 1) Definition, 2) Usage cases, 3) Benefits.",
        "user": "What is Docker?"
    }
]
for version in prompt_versions:
    print(f"\n{'='*50}")
    print(f"Version: {version['name']}")
    print(f"{'='*50}")
    
    messages = [
        SystemMessage(content=version["system"]),
        HumanMessage(content=version["user"])
    ]
    response = llm.invoke(messages)
    print(response.content[:300] + "...")

==================================================
Version: basic
==================================================
Docker is an open-source platform that **automates the deployment, scaling, and management of applications using containers.**

Think of containers as **lightweight, standalone, executable packages of software** that include everything needed to run an application: the code, runtime, system tools, s...

==================================================
Version: expert
==================================================
Alright, let's break down Docker from a DevOps perspective. Imagine you're building and deploying software, and you've probably run into the classic "it works on my machine" problem. You know, where your application runs perfectly on your laptop, but then when you try to run it on a staging server o...

==================================================
Version: structured
==================================================
Here's a breakdown of Docker from a DevOps perspective:

### 1) Definition

Docker is an open-source platform that automates the deployment, scaling, and management of applications using **containers**. A container is a lightweight, standalone, executable package of software that includes everything...

[Trace(trace_id=tr-157a516d03a508eac0ae8e8653f08f73), Trace(trace_id=tr-3286345c22cbb3fcdf1498003cd641f4), Trace(trace_id=tr-f01119081a155c585912b95eb2dfac94)]

In [73]:
import pandas as pd
import time

# Dataset de evaluación
eval_data = pd.DataFrame({
    "question": [
        "What is a Docker container?",
        "What is Kubernetes used for?",
        "What is CI/CD?"
    ],
    "expected_keywords": [
        ["software", "dependencies", "isolated"],
        ["orchestration", "containers", "scaling"],
        ["integration", "continue", "deployment"]
    ]
})

print(eval_data)

                       question                     expected_keywords
0   What is a Docker container?    [software, dependencies, isolated]
1  What is Kubernetes used for?  [orchestration, containers, scaling]
2                What is CI/CD?   [integration, continue, deployment]

In [74]:
mlflow.set_experiment("LLM_Evaluation")

with mlflow.start_run(run_name="evaluation_run"):
    results = []
    
    for idx, row in eval_data.iterrows():
        start = time.time()
        
        messages = [
            SystemMessage(content="Respond in a concise and technical manner."),
            HumanMessage(content=row["question"])
        ]
        response = llm.invoke(messages)
        
        latency = time.time() - start
        
        # Verificamos keywords presentes
        response_lower = response.content.lower()
        keywords_found = sum(1 for kw in row["expected_keywords"] if kw in response_lower)
        keyword_score = keywords_found / len(row["expected_keywords"])
        
        results.append({
            "question": row["question"],
            "response": response.content,
            "latency": latency,
            "keyword_score": keyword_score
        })
        
        mlflow.log_metric(f"latency_q{idx}", latency)
        mlflow.log_metric(f"keyword_score_q{idx}", keyword_score)
    
    # Métricas agregadas
    results_df = pd.DataFrame(results)
    mlflow.log_metric("avg_latency", results_df["latency"].mean())
    mlflow.log_metric("avg_keyword_score", results_df["keyword_score"].mean())
    
    # Guardamos resultados
    mlflow.log_table(results_df, "evaluation_results.json")
    
    print("Resultados de evaluación:")
    print(results_df[["question", "latency", "keyword_score"]])

2026/03/04 12:00:18 INFO mlflow.tracking.fluent: Experiment with name 'LLM_Evaluation' does not exist. Creating a new experiment.

Resultados de evaluación:
                       question   latency  keyword_score
0   What is a Docker container?  1.027041       0.666667
1  What is Kubernetes used for?  0.834607       0.666667
2                What is CI/CD?  1.431441       0.666667
🏃 View run evaluation_run at: http://127.0.0.1:8080/#/experiments/5/runs/638d5524d08b4337ad0add1ce1621a99
🧪 View experiment at: http://127.0.0.1:8080/#/experiments/5

[Trace(trace_id=tr-c45cb5e70c6bf461fa3a959456be07dc), Trace(trace_id=tr-e9626d04ae2eb93509642bbf246f9515), Trace(trace_id=tr-fb2db2acefe9403fd3b906a5066ae1e5)]

## Práctica parte FastAPI

### Para esta parte de la práctica teneis que generar un script con al menos 5 modulos app.get y dos de ellos tienen que ser pipelines de HF.

### Parte de la practica se tendra que entregar en capturas de pantalla. Las capturas de pantalla a adjuntas son las siguientes.

### 1. Captura de la pantalla docs con al menos 5 modulos.
### 2. Captura de cada una de los modulos con la respuesta dentro de docs.
### 3. Captura de cada uno de los modulos en la llamada https.
### 4. Todo el codigo usado durante el proceso. Notebooks y scripts.

### Opcional

### 5. Despliegue del script en GCP Cloud Run